# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Docker Run Action
      # You may pin to the exact commit or the version.
      # uses: addnab/docker-run-action@1cd63ec344892b3e6174b19bde301d071a573ade
      uses: addnab/docker-run-action@v1
      with:
        # Image
        image: basho/riak-kv
        options: -p 8087:8087 -p 8098:8098
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: sleep 30
    - run: node ./intro-to-riak.js
